version: '3.1'
services :
  db:
    image: <username>/pgtest
    ports:
      - "5432:5432"
  app:
    image: restapi:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - db
    environment:
      FOOTIE_DB_HOST: db
    ports:
      - 12080:12080
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 200M
